### ISSUE TITLE
catch error when not using any args

### ISSUE THREAD

**Issue by cedricduriau** [cedricduriau/packagerbuddy#15]
When not specifying an action, this error gets raised.

```python
Traceback (most recent call last):
  File "/home/cedricduriau/repo/packagerbuddy/bin/packagerbuddy", line 123, in <module>
    action = namespace.which
AttributeError: 'Namespace' object has no attribute 'which'
```

Fix:
- rename defaults to action (cleaner)
- set default empty action on main parser
- catch empty parser (nice colors pls)

**Comment by cedricduriau** [comment]
When not specifying an action, this error gets raised.

```python
Traceback (most recent call last):
  File "/home/cedricduriau/repo/packagerbuddy/bin/packagerbuddy", line 123, in <module>
    action = namespace.which
AttributeError: 'Namespace' object has no attribute 'which'
```

Fix:
- rename defaults to action (cleaner)
- set default empty action on main parser
- catch empty parser (nice colors pls)
